# example netlify.toml
[build]
  command = "tinacms build && astro build"
  functions = "netlify/functions"
  publish = "dist"

[dev]
  command = "astro dev"
  targetPort = 3000

#[functions]
#  external_node_modules = ["astro"]

[[redirects]]
  from = "/post/categories-pages-added"
  to = "/blog/category-pages-added"
  status = 301
  force = true
  [redirects.headers]
    X-From = "Netlify"

[[redirects]]
  from = "/post/:splat"
  to = "/blog/:splat"
  status = 301
  force = true
  [redirects.headers]
    X-From = "Netlify"

[[plugins]]
  package = "@netlify/plugin-lighthouse"
  [[plugins.inputs.audits]]
    url = "https://jeroenvanwissen.nl/"

[[headers]]
  for = "/*"
  [headers.values]
  cache-control = "max-age=0,no-cache,no-store,must-revalidate"
