# example netlify.toml
[build]
  command = "astro build"
  functions = "netlify/functions"
  publish = "dist"

[dev]
  command = "astro dev"
  targetPort = 3000

#[functions]
#  external_node_modules = ["astro"]

[[plugins]]
  package = "@netlify/plugin-lighthouse"
  [[plugins.inputs.audits]]
    url = "https://jeroenvanwissen.nl/"

[[headers]]
  for = "/*"
  [headers.values]
  cache-control = "max-age=0,no-cache,no-store,must-revalidate"

[[redirects]]
  from = "/post/*"
  to = "/blog/:splat"
  status = 301
  force = true
[[redirects]]
  from = "/blog/categories-pages-added"
  to = "/blog/category-pages-added"
  status = 301
  force = true
[[redirects]]
  from = "https://www.jeroenvanwissen.com/*"
  to = "https://jeroenvanwissen.nl/:splat"
  status = 301
  force = true
[[redirects]]
  from = "https://jeroenvanwissen.com/*"
  to = "https://jeroenvanwissen.nl/:splat"
  status = 301
  force = true
